
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/init/mc.sh"]
    volumes:
      - ./init:/init

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_started
      mc:
        condition: service_completed_successfully
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SKIP_SCHEMA_INIT: "false"
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -Djavax.jdo.option.ConnectionUserName=${POSTGRES_USER} -Djavax.jdo.option.ConnectionPassword=${POSTGRES_PASSWORD}"
    ports:
      - "${HIVE_METASTORE_PORT:-9083}:9083"
    volumes:
      - hive-warehouse:/opt/hive/warehouse

  trino:
    image: trinodb/trino:413
    container_name: trino
    depends_on:
      hive-metastore:
        condition: service_started
    ports:
      - "${TRINO_PORT:-8080}:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    depends_on:
      trino:
        condition: service_started
      postgres:
        condition: service_started
    environment:
      CB_SERVER_NAME: "${CB_SERVER_NAME}"
      CB_SERVER_URL: "${CB_SERVER_URL}"
      CB_ADMIN_NAME: "${CB_ADMIN_NAME}"
      CB_ADMIN_PASSWORD: "${CB_ADMIN_PASSWORD}"
    ports:
      - "${CLOUDBEAVER_PORT:-8978}:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    restart: unless-stopped

volumes:
  postgres-data:
  hive-warehouse:
  cloudbeaver-data: