
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/init/mc.sh"]
    volumes:
      - ./init:/init

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_started
      mc:
        condition: service_completed_successfully
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SKIP_SCHEMA_INIT: "false"
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive"
    ports:
      - "9083:9083"
    volumes:
      - hive-warehouse:/opt/hive/warehouse

  trino:
    image: trinodb/trino:413
    container_name: trino
    depends_on:
      hive-metastore:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    depends_on:
      trino:
        condition: service_started
      postgres:
        condition: service_started
    environment:
      CB_SERVER_NAME: "Lakehouse CloudBeaver"
      CB_SERVER_URL: "http://localhost:8978"
      CB_ADMIN_NAME: "admin"
      CB_ADMIN_PASSWORD: "admin123"
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    restart: unless-stopped

volumes:
  postgres-data:
  hive-warehouse:
  cloudbeaver-data: